# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/local/Documents/GitHub/source/_vhdl/constraints/basys3_7segment.xdc

# XDC: C:/Users/local/Documents/GitHub/source/_vhdl/constraints/basys3_analog.xdc

# XDC: C:/Users/local/Documents/GitHub/source/_vhdl/constraints/basys3_clock.xdc

# XDC: C:/Users/local/Documents/GitHub/source/_vhdl/constraints/basys3_flash.xdc

# XDC: C:/Users/local/Documents/GitHub/source/_vhdl/constraints/basys3_header.xdc

# XDC: C:/Users/local/Documents/GitHub/source/_vhdl/constraints/basys3_signal.xdc

# XDC: C:/Users/local/Documents/GitHub/source/_vhdl/constraints/basys3_uart.xdc

# XDC: C:/Users/local/Documents/GitHub/source/_vhdl/constraints/basys3_vga.xdc

# Block Designs: bd/vga_bd/vga_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_bd || ORIG_REF_NAME==vga_bd}]

# IP: bd/vga_bd/ip/vga_bd_clk_wiz_0_0/vga_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_bd_clk_wiz_0_0 || ORIG_REF_NAME==vga_bd_clk_wiz_0_0}]

# Block Designs: bd/clock_bd/clock_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_bd || ORIG_REF_NAME==clock_bd}]

# IP: bd/clock_bd/ip/clock_bd_clk_wiz_0_0/clock_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_bd_clk_wiz_0_0 || ORIG_REF_NAME==clock_bd_clk_wiz_0_0}]

# XDC: bd/vga_bd/ip/vga_bd_clk_wiz_0_0/vga_bd_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vga_bd_clk_wiz_0_0 || ORIG_REF_NAME==vga_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/vga_bd/ip/vga_bd_clk_wiz_0_0/vga_bd_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vga_bd_clk_wiz_0_0 || ORIG_REF_NAME==vga_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/vga_bd/ip/vga_bd_clk_wiz_0_0/vga_bd_clk_wiz_0_0_ooc.xdc

# XDC: bd/vga_bd/vga_bd_ooc.xdc

# XDC: bd/clock_bd/ip/clock_bd_clk_wiz_0_0/clock_bd_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_bd_clk_wiz_0_0 || ORIG_REF_NAME==clock_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/clock_bd/ip/clock_bd_clk_wiz_0_0/clock_bd_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_bd_clk_wiz_0_0 || ORIG_REF_NAME==clock_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/clock_bd/ip/clock_bd_clk_wiz_0_0/clock_bd_clk_wiz_0_0_ooc.xdc

# XDC: bd/clock_bd/clock_bd_ooc.xdc
